toggle_hotkey = "ALT+SPACE"
placeholder = "It's a secret"
search_url = "https://duckduckgo.com/search?q=%s"
haptic_feedback = false
show_tray_icon = true
clipboard_hotkey = "SUPER+SHIFT+C"
log_path = "~/Documents/coding/rc/target/dbglogs.log"

[buffer_rules]
clear_on_hide = true
clear_on_enter = true

[theme]
text_color = [0.95, 0.95, 0.96]
background_color = [0.09, 0.09, 0.09]
blur = false
show_icons = true
show_scroll_bar = true
font = "Iosevka"

[[shells]]
command = "~/.config/rustcast/left_half.sh"
alias = "Left half"
alias_lc = "left half"
